version: '3.8'

services:
  # Spring Boot Application
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: baskili-isler-backend
    ports:
      - "8088:8088"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - DATABASE_URL=jdbc:postgresql://baskiliisler-baskiliisler.d.aivencloud.com:14549/defaultdb?sslmode=require
      - DATABASE_USERNAME=avnadmin
      - DATABASE_PASSWORD=AVNS_cFGK5rlTGxFz9KBaivY
      - DDL_AUTO=validate
      - LOG_LEVEL=INFO
      - JWT_SECRET=myVerySecureJwtSecretKey123456789012345678901234567890
      - JWT_EXPIRATION=24H
    networks:
      - baskili-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  baskili-network:
    driver: bridge
