-- Migration v40: Multitenant Dealer Yapısı
-- Bu migration dealers tablosunu oluşturur ve tüm ana entity'lere dealer_id FK'si ekler

-- 1. Dealers tablosunu oluştur
CREATE TABLE IF NOT EXISTS dealers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(50) NOT NULL UNIQUE,
    name VARCHAR(100) NOT NULL,
    master BOOLEAN DEFAULT FALSE
);

-- 2. Master dealer'ı seed et
INSERT INTO dealers (id, code, name, master) 
VALUES (1, 'MAIN', 'Ana Bayi', true)
ON CONFLICT (id) DO NOTHING;

-- 3. Sequence'ı güncelle (ID=1 kullanıldığı için sequence'ı 2'den başlat)
SELECT setval('dealers_id_seq', 1, false);

-- 4. Tüm ana tablolara dealer_id kolonu ekle
ALTER TABLE brands ADD COLUMN IF NOT EXISTS dealer_id BIGINT;
ALTER TABLE products ADD COLUMN IF NOT EXISTS dealer_id BIGINT;
ALTER TABLE quotes ADD COLUMN IF NOT EXISTS dealer_id BIGINT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS dealer_id BIGINT;
ALTER TABLE users ADD COLUMN IF NOT EXISTS dealer_id BIGINT;

-- 5. Mevcut kayıtları master dealer'a ata
UPDATE brands SET dealer_id = 1 WHERE dealer_id IS NULL;
UPDATE products SET dealer_id = 1 WHERE dealer_id IS NULL;
UPDATE quotes SET dealer_id = 1 WHERE dealer_id IS NULL;
UPDATE orders SET dealer_id = 1 WHERE dealer_id IS NULL;
UPDATE users SET dealer_id = 1 WHERE dealer_id IS NULL AND role != 'FACTORY_USER';

-- 6. NOT NULL constraint'leri ekle (FACTORY_USER hariç)
ALTER TABLE brands ALTER COLUMN dealer_id SET NOT NULL;
ALTER TABLE products ALTER COLUMN dealer_id SET NOT NULL;
ALTER TABLE quotes ALTER COLUMN dealer_id SET NOT NULL;
ALTER TABLE orders ALTER COLUMN dealer_id SET NOT NULL;

-- 7. Foreign key constraint'leri ekle
ALTER TABLE brands ADD CONSTRAINT fk_brands_dealer 
    FOREIGN KEY (dealer_id) REFERENCES dealers(id);

ALTER TABLE products ADD CONSTRAINT fk_products_dealer 
    FOREIGN KEY (dealer_id) REFERENCES dealers(id);

ALTER TABLE quotes ADD CONSTRAINT fk_quotes_dealer 
    FOREIGN KEY (dealer_id) REFERENCES dealers(id);

ALTER TABLE orders ADD CONSTRAINT fk_orders_dealer 
    FOREIGN KEY (dealer_id) REFERENCES dealers(id);

ALTER TABLE users ADD CONSTRAINT fk_users_dealer 
    FOREIGN KEY (dealer_id) REFERENCES dealers(id);

-- 8. Index'ler ekle
CREATE INDEX IF NOT EXISTS idx_brands_dealer_id ON brands(dealer_id);
CREATE INDEX IF NOT EXISTS idx_products_dealer_id ON products(dealer_id);
CREATE INDEX IF NOT EXISTS idx_quotes_dealer_id ON quotes(dealer_id);
CREATE INDEX IF NOT EXISTS idx_orders_dealer_id ON orders(dealer_id);
CREATE INDEX IF NOT EXISTS idx_users_dealer_id ON users(dealer_id);

-- 9. PostgreSQL Row Level Security (RLS) için hazırlık
-- Bu kısım daha sonra JPA/Hibernate filter ile yönetilecek 