-- Migration v42: Dealer (Bayi/Franchise) Entegrasyonu
-- Tarih: 2024-12-19

-- 1. Dealers tablosunu oluştur
CREATE TABLE dealers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL UNIQUE,
    address TEXT,
    phone_number VARCHAR(20),
    tax_number VARCHAR(50),
    active BOOLEAN DEFAULT TRUE
);

-- 2. Default dealer oluştur (mevcut veriler için)
INSERT INTO dealers(id, name, active) VALUES (1, 'Default Dealer', true);

-- 3. Users tablosuna dealer_id kolonu ekle
ALTER TABLE users ADD COLUMN dealer_id BIGINT;
ALTER TABLE users ADD CONSTRAINT fk_users_dealer FOREIGN KEY (dealer_id) REFERENCES dealers(id);

-- 4. Brands tablosuna dealer_id kolonu ekle
ALTER TABLE brands ADD COLUMN dealer_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE brands ADD CONSTRAINT fk_brands_dealer FOREIGN KEY (dealer_id) REFERENCES dealers(id);

-- 5. Products tablosuna dealer_id kolonu ekle
ALTER TABLE products ADD COLUMN dealer_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE products ADD CONSTRAINT fk_products_dealer FOREIGN KEY (dealer_id) REFERENCES dealers(id);

-- 6. Quotes tablosuna dealer_id kolonu ekle
ALTER TABLE quotes ADD COLUMN dealer_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE quotes ADD CONSTRAINT fk_quotes_dealer FOREIGN KEY (dealer_id) REFERENCES dealers(id);

-- 7. Orders tablosuna dealer_id kolonu ekle
ALTER TABLE orders ADD COLUMN dealer_id BIGINT NOT NULL DEFAULT 1;
ALTER TABLE orders ADD CONSTRAINT fk_orders_dealer FOREIGN KEY (dealer_id) REFERENCES dealers(id);

-- 8. Mevcut verileri default dealer'a ata
UPDATE brands SET dealer_id = 1 WHERE dealer_id IS NULL;
UPDATE products SET dealer_id = 1 WHERE dealer_id IS NULL;
UPDATE quotes SET dealer_id = 1 WHERE dealer_id IS NULL;
UPDATE orders SET dealer_id = 1 WHERE dealer_id IS NULL;

-- 9. Default değerleri kaldır (artık zorunlu)
ALTER TABLE brands ALTER COLUMN dealer_id DROP DEFAULT;
ALTER TABLE products ALTER COLUMN dealer_id DROP DEFAULT;
ALTER TABLE quotes ALTER COLUMN dealer_id DROP DEFAULT;
ALTER TABLE orders ALTER COLUMN dealer_id DROP DEFAULT;

-- 10. Index'ler ekle (performans için)
CREATE INDEX idx_users_dealer_id ON users(dealer_id);
CREATE INDEX idx_brands_dealer_id ON brands(dealer_id);
CREATE INDEX idx_products_dealer_id ON products(dealer_id);
CREATE INDEX idx_quotes_dealer_id ON quotes(dealer_id);
CREATE INDEX idx_orders_dealer_id ON orders(dealer_id); 