spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://aws-0-us-east-2.pooler.supabase.com:6543/postgres?sslmode=require}
    username: ${DATABASE_USERNAME:postgres.nzpbfnqhnujvugsvuyer}
    password: ${DATABASE_PASSWORD}
    hikari:
      # Supabase Connection Pooler için optimize edilmiş ayarlar
      maximum-pool-size: 10       # Pooler ile daha yüksek limit
      minimum-idle: 2             # Minimum idle connection
      connection-timeout: 20000   # 20 saniye connection timeout
      idle-timeout: 300000        # 5 dakika idle timeout
      max-lifetime: 1800000       # 30 dakika max lifetime
      leak-detection-threshold: 60000  # 1 dakika leak detection
      pool-name: BaskiliIslerHikariCP
      auto-commit: false          # AutoCommit'i manual kapat
      
  jpa:
    hibernate:
      ddl-auto: update  # Supabase'de update kullanabiliriz
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        jdbc:
          batch_size: 25
        order_inserts: true
        order_updates: true
        connection:
          provider_disables_autocommit: true
          auto_commit: false
        
  # Actuator minimal
  management:
    endpoints:
      web:
        exposure:
          include: health
    endpoint:
      health:
        show-details: never

# SpringDoc/Swagger Production Config
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
  show-actuator: false

# App Configuration
app:
  base-url: ${APP_BASE_URL:}

# JWT Configuration
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:24H}

# Minimal Logging
logging:
  level:
    root: WARN
    com.baskiliisler: INFO
    org.springframework: WARN
    org.hibernate: ERROR
    org.apache.tomcat: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{20} - %msg%n"

# Server configuration
server:
  port: ${PORT:8088}
  error:
    include-message: never
    include-binding-errors: never
  tomcat:
    threads:
      max: 50
      min-spare: 5 