spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bis
    username: bis
    password: bis
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  flyway:
    baseline-on-migrate: true
    enabled: true

server:
  port: 8088

logging:
  level:
    root: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

jwt:
  secret: verysecretdevstring
  expiration: 30m
